apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: hello-world-app

build:
  artifacts:
    - image: europe-west3-docker.pkg.dev/ace-anthos-poc/cloud-deploy-repo/hello-world
    
deploy:
  kubectl:
    manifests:
      - kubernetes/dev/deployment.yaml  # Dev ortamı için Kubernetes manifestosu
      - kubernetes/prod/deployment.yaml  # Prod ortamı için Kubernetes manifestosu
