apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: hello-world-app

build:
  artifacts:
    - image: europe-west3-docker.pkg.dev/ace-anthos-poc/cloud-deploy-repo/hello-world
      context: .  # Uygulamanın bulunduğu dizin (Dockerfile veya Kubernetes manifestosuyla aynı dizin olabilir)
      docker:
        dockerfile: Dockerfile  # İmajı oluşturmak için kullanacağınız Dockerfile yolu
  tagPolicy:
    sha256: {}

deploy:
  kubectl:
    manifests:
      - kubernetes/dev/deployment.yaml  # Dev ortamı için Kubernetes manifestosu
      - kubernetes/prod/deployment.yaml  # Prod ortamı için Kubernetes manifestosu
