apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kuard-app
  template:
    metadata:
      labels:
        app: kuard-app
    spec:
      containers:
        - name: kuard-container
          image: europe-west3-docker.pkg.dev/ace-anthos-poc/cloud-deploy-repo/kuard-image
          ports:
            - containerPort: 8080
---
# Servic
apiVersion: v1
kind: Service
metadata:
  name: kuard-service
spec:
  selector:
    app: kuard-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer