name: Build and Push to Artifact Registry
on:
  push:
    branches:
      - main
      
permissions:
  contents: "read"
  id-token: "write" 
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/669714256369/locations/global/workloadIdentityPools/github-wi-pool/providers/github-wi-pool-provider"
          service_account: "githubactions@ace-team-nilsu-service.iam.gserviceaccount.com"
     
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Project
        run: |
          gcloud config set project ace-team-nilsu-service
      
      - name: Authenticate Docker with GCP Artifact Registry
        run: gcloud auth configure-docker europe-west3-docker.pkg.dev

      - name: Build Docker Image
        run: docker build -t europe-west3-docker.pkg.dev/ace-team-nilsu-service/helloworld-images/hello-world:latest .

      # SSH bağlantısı ve container güncelleme
      - name: SSH into VM and update container
        env:
          VM_NAME: ${{ secrets.GCP_VM_NAME }}
          VM_ZONE: ${{ secrets.GCP_VM_ZONE }}
        run: |
          gcloud compute ssh $VM_NAME \
            --zone=$VM_ZONE \
            --tunnel-through-iap \
            --command="
              mkdir nms && \
              vi nms/test.yaml"
      - name: Push Docker Image to Artifact Registry
        run: docker push europe-west3-docker.pkg.dev/ace-team-nilsu-service/helloworld-images/hello-world:latest
