name: Create Directory on GCP VM
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: "read"
  id-token: "write"

jobs:
  create-directory:
    runs-on: ubuntu-latest
    steps:
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/669714256369/locations/global/workloadIdentityPools/github-wi-pool/providers/github-wi-pool-provider"
          service_account: "githubactions@ace-team-nilsu-service.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Project
        run: |
          gcloud config set project ace-team-nilsu-service
          gcloud config list

      - name: Check Instance Status
        run: |
          gcloud compute instances describe test-nilsu \
            --zone=europe-west3-c \
            --format='get(status)'

      - id: 'compute-ssh'
        uses: 'google-github-actions/ssh-compute@v1'
        with:
          instance_name: 'test-nilsu'
          zone: 'europe-west3-c'
          ssh_private_key: '${{ secrets.SSH_PRIVATE_KEY }}'
          command: 'echo Hello && whoami && mkdir nilsu-github-test'
          user: 'nilsu_sonmez'

    # Example of using the output
      - id: 'test'
        run: |-
          echo '${{ steps.compute-ssh.outputs.stdout }}'
          echo '${{ steps.compute-ssh.outputs.stderr }}'
